# Generated by Django 3.1.8 on 2022-08-31 23:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_views'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('most_read_posts', django.db.models.manager.Manager()),
            ],
        ),
    ]
